language: go
services:
  - docker
script:
- make build
- test -f bin/linux_amd64/workerpodautoscaler
- make all-container
- docker images | grep "^public.ecr.aws/practo/workerpodautoscaler"
- make test
