apiVersion: apps/v1
kind: Deployment
metadata:
 name: workerpodautoscaler
 namespace: kube-system
 labels:
   app: workerpodautoscaler
spec:
 replicas: 1
 selector:
   matchLabels:
     app: workerpodautoscaler
 template:
   metadata:
     labels:
       app: workerpodautoscaler
   spec:
     serviceAccountName: workerpodautoscaler
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     containers:
     - name: wpa
       env:
       - name: AWS_ACCESS_KEY_ID
         value: {{ WPA_AWS_ACCESS_KEY_ID }}
       - name: AWS_SECRET_ACCESS_KEY
         value: {{ WPA_AWS_SECRET_ACCESS_KEY }}
      #  image: public.ecr.aws/practo/workerpodautoscaler:{{ WPA_TAG }}
       image: us-central1-docker.pkg.dev/d-reconstruction-server/data-processing-k8s-worker-pod-autoscaler-repository/workerpodautoscaler@sha256:1b8c8aaf956124f1c4a2d32e06dca0b9c1634fc7716aba0f863bdab507a9472d
       imagePullPolicy: Always
       command:
       - /workerpodautoscaler
       - run
       - --resync-period=20
       - --wpa-threads=10
       - --aws-regions={{ WPA_AWS_REGIONS }}
       - --sqs-short-poll-interval=20
       - --sqs-long-poll-interval=20
       - --k8s-api-qps=5.0
       - --k8s-api-burst=10
       - --wpa-default-max-disruption=100%
       - --queue-services=sqs,beanstalkd
       - -v=2
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi